class Company:
    def __init__(self, obj):
        self.name = obj.get("name", " ")
        self.source = obj.get("source", " ")
        self.article = obj.get("article", " ")
        self.profit = obj.get("profit", " ")
        self.company_id = obj.get("company_id", " ")
        self.headquarters = obj.get("headquarters", " ")
        self.assets = obj.get("assets", " ")
        self.operating_years = obj.get("operating_years", " ")
        self.last_quarterly_revenue = obj.get("last_quarterly_revenue", " ")
        self.founded = obj.get("founded", " ")
        self.specialties = obj.get("Specialties", " ")
        self.type = obj.get("type", " ")
        self.market_value = obj.get("market_value", " ")
        self.slogan = obj.get("Slogan", " ")
        self.company_size = obj.get("company_size", " ")
        self.affiliated_companies = obj.get("affiliated_companies", " ")
        self.country = obj.get("country", " ")
        self.about = obj.get("About", " ")
        self.no_of_employees = obj.get("no_of_employees", " ")
        self.categories = obj.get("Categories", " ") 
        self.yearly_revenue_2021 = obj.get("yearly_revenue_2021", " ")
        self.second_last_quarterly_revenue = (
                           obj.get("second_last_quarterly_revenue"), " ")
        self.industry = obj.get("industry", " ")
        self.social_url = obj.get("social_url", " ")
        self.similar_companies = obj.get("similar_companies", " ")
        self.description = obj.get("description", " ")
        self.social_followers = obj.get("social_followers", " ") 
        self.revenue_dollar = obj.get("revenue_dollar", " ")
        self.revenue_dollar = obj.get("revenue_dollar", " ")
        self.company_linkedin_name = obj.get("company_linkedin_name", " ")
        self.website = obj.get("website", " ")
        self.annual_growth = obj.get("annual_growth", " ")
        self.quarterly_growth = obj.get("quarterly_growth", " ")
        self.vector_score = obj.get("vector_score", " ")